# Generated by Django 6.0.5 on 2026-06-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField(db_column='IMC')),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('glucosa', models.FloatField()),
                ('colesterol', models.FloatField()),
                ('saturacion_oxigeno', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('antecedentes_familiares', models.BooleanField()),
                ('fumador', models.BooleanField()),
                ('consumo_alcohol', models.BooleanField()),
                ('actividad_fisica', models.CharField(max_length=50)),
                ('diagnostico_preliminar', models.CharField(max_length=100)),
                ('riesgo_enfermedad', models.CharField(max_length=50)),
                ('fecha_consulta', models.DateField()),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'patients_patient',
            },
        ),
    ]
