# Generated by Django 6.0.5 on 2026-06-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(default='RandomForestClassifier', max_length=128)),
                ('dataset_size', models.PositiveIntegerField(default=0)),
                ('feature_schema', models.JSONField(default=list)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.JSONField(blank=True, null=True)),
                ('recall', models.JSONField(blank=True, null=True)),
                ('f1_score', models.JSONField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=64)),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_logs', to='ml.modelversion')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='patients.patient')),
            ],
        ),
    ]
